# Generated by Django 2.1.1 on 2018-10-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, default='contoso@example.com', max_length=75, null=True)),
                ('passwd', models.CharField(max_length=30)),
            ],
        ),
    ]
