# Generated by Django 2.1.1 on 2018-10-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
